#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

. `dirname $0`/bigtop.bom

SCALA_BIN_VERSION=`echo $SCALA_VERSION | awk -F"." '{print $1}'`.`echo $SCALA_VERSION | awk -F"." '{print $2}'`

#BUILD_OPTS="-Divy.home=${HOME}/.ivy2 -Dsbt.ivy.home=${HOME}/.ivy2 -Duser.home=${HOME} \
#            -Drepo.maven.org=$IVY_MIRROR_PROP \
#            -Dreactor.repo=file://${HOME}/.m2/repository \
#            -Dhadoop.version=$HADOOP_VERSION \
#            -Dalluxio.version=$ALLUXIO_VERSION \
#            -Delasticsearch.version=$ELASTICSEARCH_VERSION \
#            -Dflink.version=$FLINK_VERSION \
#            -Pscala-2.11 -Dscala.version=$SCALA_VERSION \
#            -Pbuild-distr"

BUILD_OPTS="-Divy.home=${HOME}/.ivy2 -Dsbt.ivy.home=${HOME}/.ivy2 -Duser.home=${HOME} \
            -Drepo.maven.org=$IVY_MIRROR_PROP \
            -Dreactor.repo=file://${HOME}/.m2/repository \
            -Dhadoop.version=$HADOOP_VERSION \
            -Delasticsearch.version=$ELASTICSEARCH_VERSION \
            -Dflink.version=$FLINK_VERSION \
            -Pscala-2.11 -Dscala.version=$SCALA_VERSION \
            -Pbuild-distr"

BUILD_OPTS="$BUILD_OPTS -DskipTests -Dcheckstyle.skip"

export MAVEN_OPTS="-Xmx1500m -Xms1500m -XX:MaxPermSize=256m"

mvn clean package $BUILD_OPTS
